files:
  include: 'scss/templates/*.s+(a|c)ss'
  ignore: 'app/design/frontend/Oander/hodor/web/scss/styles/vendors/**/*.s+(a|c)ss'

# Rule Configuration
# reference: https://github.com/sasstools/sass-lint/tree/master/docs/rules/
rules:

  indentation:
  - 1
  - size: 2

  # Disable nesting validation
  nesting-depth:
  - 0
  - max-depth: 4

  # Disable 'force variable using to colors'
  no-color-literals:
  - 0

  property-sort-order:
  - 1
  - order: smacss

  force-attribute-nesting:
  - 0

  force-element-nesting:
  - 0

  force-pseudo-nesting:
  - 0

  class-name-format:
  - 0

  no-qualifying-elements:
  - 0

  no-url-domains:
  - 0

  no-url-protocols:
  - 0

  placeholder-in-extend:
  - 0

  no-important:
  - 0

  leading-zero:
  - 1

  border-zero:
  - 1
  - convention: 'none'

  clean-import-paths:
  - 0

  max-file-line-count:
  - 1
  - length: 600

  variable-name-format:
  - 0

  function-name-format:
  - 0

  no-ids:
  - 0
